### ISSUE TITLE
had a look at it....

### ISSUE THREAD

**Issue by JanEggers** [dealproc/MQTTnet.Orleans#1]
https://github.com/dealproc/MQTTnet.Orleans/blob/3544a9f1879f13f29315a9ebcdff9e7872121808/source/MQTTnet.Orleans/OrleansManagedMqttServer.cs#L53

you should really add try catch block to async void if you get an exception there it will tear down the app.

**Comment by dealproc** [comment]
Hey man... Thanks for catching that... give me a few moments and i'll patch it and push it up.

**Comment by dealproc** [comment]
Need to lay this back into main repo now and test... Do you have a suggestion on a way where a nuget can be created so that you don't need to capture the code to do your work? (e.g. if you would be willing to setup the circleci ci/cd pipeline @JanEggers, I'd be willing to give you access to the repo to do it. I'm just not familiar with the CircleCI, or I would attempt it on my own.)

**Comment by JanEggers** [comment]
have a look at https://github.com/marketplace/category/continuous-integration
and https://www.myget.org

but sorry I really have not enough time on my hand to set that up for you
